---
# 1) 파일 배포
# 2) 파일 작성
# 3) 파일 수집
- name: Play01 -하드웨어 보고서 작성
  hosts: all
  tasks:
    # 1) 파일 배포
    # files/hwreport.txt -> ansible#:/root/hwreport.txt
    - name: 1) 파일 배포
      ansible.builtin.copy:
      src: files/hwreport.txt
        dest: /root/hwreport.txt
        owner: root
        group: root
        mode: '0600'

- name: 3) 파일 수집
  ansible.builtin.fetch:
    src: /root/hwreport.txt
    dest: results/
    flat: false



















    # 2) 파일 작성
    # * INVENTORY_HOSTNAME
    # * TOTAL_MEM
    # * BIOS_VER
    # * SDA_SIZE
    - name: 2) 파일 작성 - {{ inventory_hostname }}
      ansible.builtin.replace:
        path: "{{ hwreportfile }}"
        regexp: 'inventoryhostname'
        replace: "{{ inventory_hostname }}"

    - name: 2) 파일 작성 - {{ ansible_facts['memtotal_mb'] }}
      ansible.builtin.replace:
        path: "{{ hwreportfile }}"
        regexp: 'totalmem'
        replace: "{{ ansible_facts['memtotal_mb'] }}"

    - name: 2) 파일 작성 - {{ ansible_facts['bios_version'] }}
      ansible.builtin.replace:
        path: "{{ hwreportfile }}"
        regexp: 'biosversion'
        replace: "{{ ansible_facts['bios_version'] }}"

    - name: 2) 파일 작성 - {{ ansible_facts['devices']['sda']['size'] }}
      ansible.builtin.replace:
        path: "{{ hwreportfile }}"
        regexp: 'sdasize'
        replace: "{{ ansible_facts['devices']['sda']['size'] }}"

    # 3) 파일 수집
    # /root/hwreport.txt -> results/*
    - name: 3) 파일 수집
      ansible.builtin.fetch:
        src: /root/hwreport.txt
        dest: results/{{ inventory_hostname }}-hwreport.txt
        flat: true
-
-
-
-
